# Generated by Django 4.2.1 on 2023-05-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'STARTER'), ('2', 'MAIN COURSE'), ('3', 'DESSERT')], default='2', max_length=2),
        ),
    ]
