# Generated by Django 4.2.1 on 2023-05-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_total_check_alter_order_total_tip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
