# Generated by Django 4.2.1 on 2023-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_percentage_tip_alter_order_waiter_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state', '1')), fields=('table_id', 'customer_id'), name='unique_order_table_customer'),
        ),
    ]
